language: python
python:
- "2.7"
- "3.4"
before_install:
  - sudo apt-get install -y libasound2-dev
install:
- pip install .
- pip install -r requirements.txt -r test-requrements.txt
script: testr init && testr run
